### PR TITLE
added a inhibitor

### PR DESCRIPTION
**Pull request by ringo32**
inhibtor not to start the screensaver for what reason

### CODE REVIEW

**Comment by ringo32** [comment]
waybar have a inhibit function for presentation, naturaly... when you click on it you do it on or off 
afbeelding

**Comment by ringo32** [comment]
afbeelding

with a strip it doesnt go to sleep

**Review by OdiousImp2604 — APPROVED** [review]
Sorry forgot about it! Nice addition

**Comment by OdiousImp2604** [comment]
Give me tmrw just to see out and see perhaps if it conflita with something

**Pull request merged**
